# Generated by Django 3.1.2 on 2020-10-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0003_auto_20201006_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=1200, verbose_name='Наименование'),
        ),
    ]
