# Generated by Django 3.1.2 on 2020-10-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0005_auto_20201006_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='clients_group',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Группа клиентов'),
        ),
    ]
