# Generated by Django 3.1.2 on 2020-10-08 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0013_auto_20201008_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nomenclature.service')),
                ('services', models.CharField(max_length=1)),
            ],
            bases=('nomenclature.service',),
        ),
    ]
