# Generated by Django 3.1.2 on 2020-10-08 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0016_auto_20201008_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование типа')),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclature.servicetype', verbose_name='Тип услуги'),
        ),
    ]
