# Generated by Django 3.1.2 on 2020-11-03 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0018_uploadfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfiles',
            name='files',
        ),
        migrations.AddField(
            model_name='uploadfiles',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='файл'),
        ),
        migrations.AddField(
            model_name='uploadfiles',
            name='filename',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='имя файла'),
        ),
        migrations.AddField(
            model_name='uploadfiles',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclature.service', verbose_name='Услуга'),
        ),
    ]
