# Generated by Django 3.1.2 on 2020-11-06 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0020_auto_20201106_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfiles',
            old_name='my_file',
            new_name='file',
        ),
    ]
