# Generated by Django 3.1.2 on 2020-12-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0026_auto_20201202_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='sex',
            field=models.CharField(choices=[('M', 'Муж.'), ('F', 'Жен.'), ('A', 'Любой')], default='Любой', max_length=10, verbose_name='Пол'),
        ),
    ]
