# Generated by Django 3.1.2 on 2020-12-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0029_test_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='measure_unit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Единицы измерения'),
        ),
    ]
