# Generated by Django 3.1.2 on 2020-12-09 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0030_auto_20201209_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='MadicineData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alter_name_KC', models.TextField(blank=True, null=True, verbose_name='Альтернативные названия для КЦ')),
                ('alter_name', models.TextField(blank=True, null=True, verbose_name='Альтернативные названия')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('volume_pp', models.TextField(blank=True, null=True, verbose_name='Объём ПП')),
                ('container_pp', models.TextField(blank=True, null=True, verbose_name='Контейнер для ПП')),
                ('guide_pp', models.TextField(blank=True, null=True, verbose_name='Инструкция по взятию ПП')),
                ('transport_conditions', models.TextField(blank=True, null=True, verbose_name='Условия транспортировки')),
                ('term_assign', models.TextField(blank=True, null=True, verbose_name='Срок доназначения')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('method', models.TextField(blank=True, null=True, verbose_name='Метод исследования')),
                ('factors', models.TextField(blank=True, null=True, verbose_name='Влияние различных факторов на результат')),
                ('preparation', models.TextField(blank=True, null=True, verbose_name='Подготовка к исследованию')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclature.service')),
            ],
        ),
    ]
