# Generated by Django 3.0.8 on 2020-10-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='biomaterials',
            field=models.CharField(blank=True, max_length=256, verbose_name='Биоматериалы'),
        ),
        migrations.AddField(
            model_name='service',
            name='blanks',
            field=models.CharField(blank=True, max_length=256, verbose_name='Бланки'),
        ),
        migrations.AddField(
            model_name='service',
            name='container',
            field=models.CharField(blank=True, max_length=256, verbose_name='контейнеры'),
        ),
        migrations.AddField(
            model_name='service',
            name='due_date',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='срок выполнения'),
        ),
        migrations.AddField(
            model_name='service',
            name='result_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='тип результата'),
        ),
    ]
