# Generated by Django 3.1.2 on 2020-10-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0007_auto_20201006_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
