# Generated by Django 3.1.2 on 2020-10-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0008_auto_20201006_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='kdl_service_key',
            field=models.CharField(max_length=50, null=True, verbose_name='Кдл. Услуга. Ключ'),
        ),
        migrations.AlterField(
            model_name='service',
            name='kdl_service_perm_code',
            field=models.CharField(max_length=50, null=True, verbose_name='Кдл. Услуга. Пермь. Код'),
        ),
        migrations.AlterField(
            model_name='service',
            name='tcle_abbreviation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ключ (аббревиатура) услуги в TCLE'),
        ),
        migrations.AlterField(
            model_name='service',
            name='tcle_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код услуги в TCLE'),
        ),
    ]
