# Generated by Django 3.1.2 on 2020-10-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0009_auto_20201006_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='blanks',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Бланки'),
        ),
    ]
