# Generated by Django 3.1.2 on 2020-10-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0014_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профили'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуги'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='services',
        ),
        migrations.AddField(
            model_name='profile',
            name='services',
            field=models.ManyToManyField(related_name='услуги', to='nomenclature.Service'),
        ),
    ]
