# Generated by Django 3.1.2 on 2020-11-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0017_auto_20201008_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.ManyToManyField(related_name='Услуга', to='nomenclature.Service')),
            ],
        ),
    ]
