# Generated by Django 3.1.2 on 2020-12-02 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0023_auto_20201202_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='test_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomenclature.testset', verbose_name='Набор тестов'),
        ),
    ]
