# Generated by Django 3.1.2 on 2020-12-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0024_service_test_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='clinic_interpretation_key',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ключ клинической интерпретации'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='clinic_interpretation_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Наименование клинической интерпретации'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='clinic_interpretation_text',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Текс клинической интерпретации'),
        ),
    ]
