# Generated by Django 3.1.2 on 2020-12-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0025_auto_20201202_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='sex',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский'), ('A', 'Любой')], default='Любой', max_length=10, verbose_name='Пол'),
        ),
    ]
