# Generated by Django 3.1.2 on 2020-12-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0027_auto_20201208_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='age_from',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Возраст с'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='age_to',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Возраст по'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='clinic_interpretation_key',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ключ клинической интерпретации'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='clinic_interpretation_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Наименование клинической интерпретации'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='clinic_interpretation_text',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Текс клинической интерпретации'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='lower_normal_value',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True, verbose_name='Норма нижняя'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='normal_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Норма текстом'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='sex',
            field=models.CharField(choices=[('M', 'Муж.'), ('F', 'Жен.'), ('A', 'Любой')], default='Любой', max_length=10, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='upper_normal_value',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True, verbose_name='Норма верхняя'),
        ),
    ]
