# Generated by Django 3.1.2 on 2020-12-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0028_auto_20201208_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Наименование теста'),
        ),
    ]
